### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ROCA

### ISSUE THREAD

**Issue by WenZhiKun** [cangumeli/ROCA#11] opened 2022-09-29 12:48 UTC
Hello @cangumeli,
Sorry to bother you, but I am getting the following error while running the `demo.py` with `model_best.pth`
Appreciate any help!

```
File "/home/aston/Desktop/python/ROCA-main/network/roca/engine/predictor.py", line 44, in __init__
    model.load_state_dict(backup['model'])
  File "/home/aston/anaconda3/envs/roca/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ROCA:
	Unexpected key(s) in state_dict: "pixel_mean", "pixel_std", "proposal_generator.anchor_generator.cell_anchors.0", "proposal_generator.anchor_generator.cell_anchors.1", "proposal_generator.anchor_generator.cell_anchors.2", "proposal_generator.anchor_generator.cell_anchors.3", "proposal_generator.anchor_generator.cell_anchors.4". 

Process finished with exit code 1
```

**Comment by WenZhiKun** [comment] 2022-09-30 00:39
I have sloved this problem by removing the `Unexpected key(s) in state_dict`

**Comment by cangumeli** [comment] 2022-10-04 00:04
Could you please check your detectron2 version? Also make sure demo produces the expected results, these keys seem like metadata that we did not explicitly modify.

**Comment by WenZhiKun** [comment] 2022-10-05 01:32
Thank you for your answer!
Well, I found that my detectron2 version is 0.6 which is higher than the version you suggest. I haved maked some adjustments and  achieved the expected results. 

> Could you please check your detectron2 version? Also make sure demo produces the expected results, these keys seem like metadata that we did not explicitly modify.

**Comment by cangumeli** [comment] 2022-10-06 01:48
Ok cool, then closing this issue since the issue is solved.

**Closed as completed by cangumeli** 2022-10-06 01:48 UTC

**Comment by csyhping** [comment] 2024-07-31 11:49
For anyone with similar issues, I strongly suggest that you install pytorch -> pytorch3d very first, making sure there is no conflict between these two. 

And please be careful of the versions; since many libraries are already out of fashion, you must ensure you use the same old version as the author.
